### ISSUE TITLE
[BUG] Envoy Does Not Respect ENVOY_LOG_LEVEL Setting from Service Connect Agent in AWS App Mesh

### ISSUE THREAD

**Issue by Penghaow** [aws/amazon-ecs-service-connect-agent#76]
### Summary

In the AWS App Mesh scenario, the Service Connect Agent is utilized to generate static bootstrap configurations for Envoy proxies. Despite this setup, there is an observed issue where Envoy logs do not respect the `ENVOY_LOG_LEVEL` setting specified by the Service Connect Agent. This behavior is unexpected.

### Description

When setting the ENVOY_LOG_LEVEL to `off` via the Service Connect Agent, Envoy sidecar containers continue to output logs at the info level. Despite correctly setting this environment variable [here](https://github.com/aws/amazon-ecs-service-connect-agent/blob/main/agent/logging/agent_logging.go/#L274), it appears that Envoy is not respecting the specified log level.

### Expected Behavior
Envoy should not produce any logs when `ENVOY_LOG_LEVEL` is set to `off`, as per the configuration defined by the Service Connect Agent.

### Observed Behavior
Envoy continues to output logs at the `info` level, disregarding the `ENVOY_LOG_LEVEL` set to `off`. More detailed in this [ticket](https://t.corp.amazon.com/V1330340239/communication)

**Comment by liubnu** [comment]
https://github.com/aws/aws-app-mesh-roadmap/issues/492
